version: 2
jobs:
  build:
    docker:
       - image: quay.io/dhtech/puppet-ci:latest
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: puppet lint
          command: |
            puppet-lint

      - run:
          name: erb check
          command: |
            rails-erb-lint
