name: puppet linting
on:
  pull_request:
    branches:
      - master
      - main
      - production
    paths-ignore:
      - "**.md"

jobs:
  puppet-lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: puppet-lint
      uses: scottbrenner/puppet-lint-action@v1.0.4
      with:
        args: ./
        
