name: puppet linting
on:
  pull_request:
    branches:
      - master
      - main
      - production
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: puppet/puppet-dev-tools:latest  # Use the community-maintained Docker image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Puppet lint
        run: |
          puppet-lint --no-puppet_url_without_modules-check --fail-on-warnings .
